// Generates the monochrome padlock app icon (build/icon.png) and the tray icon
// module (src/main/trayIcon.ts) with a tiny dependency-free PNG encoder.
import { deflateSync } from 'node:zlib';
import { writeFileSync, mkdirSync } from 'node:fs';

const CRC_TABLE = new Uint32Array(256).map((_, n) => {
  let c = n;
  for (let k = 0; k < 8; k++) c = c & 1 ? 0xedb88320 ^ (c >>> 1) : c >>> 1;
  return c >>> 0;
});
const crc32 = (buf) => {
  let c = 0xffffffff;
  for (const b of buf) c = CRC_TABLE[(c ^ b) & 0xff] ^ (c >>> 8);
  return (c ^ 0xffffffff) >>> 0;
};
function chunk(type, data) {
  const len = Buffer.alloc(4);
  len.writeUInt32BE(data.length);
  const td = Buffer.concat([Buffer.from(type, 'ascii'), data]);
  const crc = Buffer.alloc(4);
  crc.writeUInt32BE(crc32(td));
  return Buffer.concat([len, td, crc]);
}
function png(size, rgba) {
  const ihdr = Buffer.alloc(13);
  ihdr.writeUInt32BE(size, 0);
  ihdr.writeUInt32BE(size, 4);
  ihdr[8] = 8; ihdr[9] = 6; ihdr[10] = 0; ihdr[11] = 0; ihdr[12] = 0;
  const raw = Buffer.alloc((size * 4 + 1) * size);
  for (let y = 0; y < size; y++) {
    raw[y * (size * 4 + 1)] = 0;
    rgba.copy(raw, y * (size * 4 + 1) + 1, y * size * 4, (y + 1) * size * 4);
  }
  return Buffer.concat([
    Buffer.from([0x89, 0x50, 0x4e, 0x47, 0x0d, 0x0a, 0x1a, 0x0a]),
    chunk('IHDR', ihdr),
    chunk('IDAT', deflateSync(raw)),
    chunk('IEND', Buffer.alloc(0))
  ]);
}

// Shapes in a unit square [0,1]. Returns coverage of "white" and "background".
function sdRoundRect(x, y, cx, cy, hw, hh, r) {
  const dx = Math.abs(x - cx) - hw + r;
  const dy = Math.abs(y - cy) - hh + r;
  return Math.min(Math.max(dx, dy), 0) + Math.hypot(Math.max(dx, 0), Math.max(dy, 0)) - r;
}
function lockShape(x, y) {
  // shackle: ring (upper half) + legs
  const cx = 0.5, cy = 0.40, R = 0.165, T = 0.055;
  let inShackle = false;
  if (y <= cy) inShackle = Math.abs(Math.hypot(x - cx, y - cy) - R) <= T / 2;
  else if (y <= 0.52) inShackle = Math.abs(Math.abs(x - cx) - R) <= T / 2;
  const body = sdRoundRect(x, y, 0.5, 0.635, 0.24, 0.18, 0.04) <= 0;
  const hole = Math.hypot(x - 0.5, y - 0.6) <= 0.042 || (Math.abs(x - 0.5) <= 0.018 && y >= 0.6 && y <= 0.7);
  return (inShackle || body) && !hole;
}
function render(size, { background }) {
  const out = Buffer.alloc(size * size * 4);
  const ss = 4;
  for (let py = 0; py < size; py++) {
    for (let px = 0; px < size; px++) {
      let white = 0, bg = 0;
      for (let sy = 0; sy < ss; sy++) for (let sx = 0; sx < ss; sx++) {
        const x = (px + (sx + 0.5) / ss) / size;
        const y = (py + (sy + 0.5) / ss) / size;
        if (lockShape(x, y)) white++;
        else if (background && sdRoundRect(x, y, 0.5, 0.5, 0.5, 0.5, 0.18) <= 0) bg++;
      }
      const n = ss * ss;
      const i = (py * size + px) * 4;
      const a = (white + bg) / n;
      const v = white + bg ? (white * 255) / (white + bg) : 0;
      out[i] = out[i + 1] = out[i + 2] = Math.round(v);
      out[i + 3] = Math.round(a * 255);
    }
  }
  return png(size, out);
}

mkdirSync('build', { recursive: true });
mkdirSync('src/renderer/public', { recursive: true });
writeFileSync('build/icon.png', render(256, { background: true }));
writeFileSync('src/renderer/public/icon.png', render(64, { background: true }));
const tray = render(32, { background: false }).toString('base64');
const trayBg = render(32, { background: true }).toString('base64');
writeFileSync(
  'src/main/trayIcon.ts',
  `// Generated by scripts/make-icons.mjs — monochrome padlock icons (PNG, base64).\n` +
    `export const TRAY_ICON_PNG = '${tray}';\n` +
    `export const APP_ICON_PNG = '${trayBg}';\n`
);
console.log('icons written');
